version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=loginDB
    container_name: mysql
    network_mode: host
    hostname: localhost

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    - mysql
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    container_name: eureka-server-docker
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      depends_on:
      - eurekaserver
      - mysql
      ports:
      - 8888:8888
      expose:
      - 8888


  user-login:
    image: user-service
    build: user-authentication/
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8095:8095
    expose:
      - 8095

  user-service:
    image: userservice
    build: userservice/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8999:8999
    expose:
      - 8999


  question-manager-service:
    image: question-manager-service
    build: question-manager-service/
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8001:8001
    expose:
      - 8001



