version: "2"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    ports:
      - "27017:27017"
    container_name: mongo
    network_mode: host

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888


  user-login:
    image: user-service
    build: user-authentication/
    restart: always
    network_mode: host
    depends_on:
      - mysql
    ports:
      - 8090:8090
    expose:
      - 8090

  user-service:
    image: userservice
    build: userservice/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8999:8999
    expose:
      - 8999





