#eureka:
#    client:
#        fetch-registry: true
#        register-with-eureka: true
#        serviceUrl:
#            defaultZone: http://localhost:9091/eureka/
#server:
#    port: 8193
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
fetch-registry: true
##management:
##    security:
##        enabled: false
register-with-eureka: true
server:
    port: 8089
spring:
    application:
        name: Muzix Application
